add_newline = false

[character]
success_symbol = "[âœ](bold green)"

# Clear visibility for exit codes
[status]
style = "bg:red"
symbol = "ğŸ’£ "
format = '[\[$symbol$status\]]($style) '
disabled = false

# These symbols will only show when battery levels are 20% or less
[battery]
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]  # "bold red" style when capacity is between 0% and 20%
threshold = 40 
style = "bold red"

#[python]
#python_binary = "python3"

[swift]
symbol = "ï¯£ (orange)"


